#!{{pkgPathFor "core/bash"}}/bin/bash

cd {{pkg.svc_path}}/data

if [[ ! -f "{{pkg.svc_path}}/data/server.crt" ]] || [[ ! -f "{{pkg.svc_path}}/data/server.key" ]] || [[ ! -f "{{pkg.svc_path}}/data/ca.crt" ]]; then
  cp {{pkg.path}}/scripts/tls/openssl.conf .

  {{#if cfg.certificate.sans ~}}
    export SAN={{cfg.certificate.sans}}
  {{else ~}}
    export SAN=IP.1:{{cfg.grpc.address}}
  {{/if ~}}

  {{pkgPathFor "core/bash"}}/bin/bash {{pkg.path}}/scripts/tls/cert-gen
fi
