#!/bin/bash

cd "{{pkg.svc_path}}"

exec matchbox \
  -address="{{cfg.address}}:{{cfg.port}}" \
  -rpc-address="{{cfg.grpc.address}}:{{cfg.grpc.port}}" \
  -cert-file="{{pkg.svc_data_path}}/server.crt" \
  -key-file="{{pkg.svc_data_path}}/server.key" \
  -ca-file="{{pkg.svc_data_path}}/ca.crt" \
  -data-path="{{pkg.path}}/var" \
  -assets-path="{{pkg.svc_var_path}}"
