---
systemd:
  units:
    - name: etcd-member.service
      enable: true
      dropins:
        - name: 40-etcd-cluster.conf
          {{ if .controller }}
          contents: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v3.2.0"
            Environment="ETCD_NAME={{.etc_name}}"
            Environment="ETCD_ADVERTISE_CLIENT_URLS=http://{{.hostname}}:2379"
            Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://{{.hostname}}.cerny.cc:2380"
            Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
            Environment="ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
            Environment="ETCD_INITIAL_CLUSTER={{.etcd_initial_cluster}}"
            Environment="ETCD_STRICT_RECONFIG_CHECK=true"
          {{ else }}
          contents: |
            [Service]
            Environment="ETCD_IMAGE_TAG=v3.2.0"
            ExecStart=/usr/lib/coreos/etcd-wrapper gateway start \
              --listen-addr=127.0.0.1:2379 \
              --endpoints={{.etcd_endpoints}}
          {{ end }}
    - name: flanneld.service
      dropins:
        - name: 50-network-config.conf
          contents: |
            [Service]
            ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
    - name: hab-installer.service
      enable: true
      contents: |
        [Unit]
        Requires=network-online.target
        After=network-online.target
        [Service]
        Type=oneshot
        ExecStart=/opt/hab-installer
        [Install]
        WantedBy=multi-user.target
    - name: hab-sup.service
      enable: true
        contents: |
          [Unit]
          Description = The Habitat Supervisor
          [Service]
          ExecStart = /opt/bin/hab sup run --peer 192.168.2.2 --peer 192.168.2.3 --auto-update
          Restart = on-failure
          Delegate = yes
          KillMode = process
          [Install]
          WantedBy = default.target
storage:
  files:
    - path: /opt/hab-installer
      filesystem: root
      mode: 0500
      contents:
        inline: |
          #!/bin/bash -ex
          if [ ! -f "/opt/bin/hab" ]; then
            curl --retry 10 --fail https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux -o /tmp/hab.tar.gz
            tar -xvzf /tmp/hab.tar.gz -C /opt/bin
            chmod +x /opt/bin/hab
          fi
    - path: /etc/hostname
      filesystem: root
      mode: 0644
      contents:
        inline:
          {{.hostname}}
flannel:
  interface: bond1
update:
  group: stable
locksmith:
  reboot_strategy: etcd-lock
networkd:
  units:
    - name: 00-bond0-slaves.network
      contents: |
        [Match]
        Driver=bnx2
        Driver=igb
        Driver=e1000*
        [Network]
        Bond=bond0
    - name: 00-bond1-slaves.network
      contents: |
        [Match]
        Driver=mlx4*
        Driver=ixgbe
        [Network]
        Bond=bond1
        [Link]
        MTUBytes=9000
    - name: 10-bond0.netdev
      contents: |
        [NetDev]
        Name=bond0
        Kind=bond
    - name: 10-bond1.netdev
      contents: |
        [NetDev]
        Name=bond1
        Kind=bond
    - name: 20-bond0.network
      contents: |
        [Match]
        Name=bond0
        [Network]
        DHCP=false
        Address={{.bond0_ipv4}}/24
        Gateway=192.168.20.1
        DNS=192.168.2.2
        DNS=192.168.2.3
    - name: 20-bond1.network
      contents: |
        [Match]
        Name=bond1
        [Network]
        DHCP=false
        Address={{.bond1_ipv4}}/24
        [Link]
        MTUBytes=9000

{{ if index . "ssh_authorized_keys" }}
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
