---
systemd:
  units:
    - name: hab-extract.path
      enable: true
      contents: |
        [Unit]
        Description=Extract Habitat CLI
        [Path]
        PathExists=/opt/bin/hab.tar.gz
        [Install]
        WantedBy=default.target
    - name: hab-extract.service
      contents: |
        [Unit]
        Description=Extract Habitat CLI
        [Service]
        ExecStart=/usr/bin/tar xzf /opt/bin/hab.tar.gz -C /opt/bin --strip-components=1
    - name: hab-sup.service
      enable: true
      contents: |
        [Unit]
        Description=The Habitat Supervisor
        [Service]
        ExecStart=/opt/bin/hab sup run --peer 192.168.2.11 --peer 192.168.2.12 --auto-update
        Restart=on-failure
        Delegate=yes
        KillMode=process
        [Install]
        WantedBy=default.target
storage:
  files:
    - path: /opt/bin/hab.tar.gz
      filesystem: root
      contents:
        remote:
          url: https://api.bintray.com/content/habitat/stable/linux/x86_64/hab-%24latest-x86_64-linux.tar.gz?bt_package=hab-x86_64-linux
    - path: /etc/hostname
      filesystem: root
      mode: 0644
      contents:
        inline:
          {{.hostname}}
{{ if index . "controller" }}
etcd:
  version: "3.2.13"
  advertise_client_urls: http://{{.hostname}}:2379
  initial_advertise_peer_urls: http://{{.hostname}}:2380
  listen_client_urls: http://0.0.0.0:2379
  listen_peer_urls: http://0.0.0.0:2380
  initial_cluster: {{.etcd_initial_cluster}}
  name: ((.etcd_name))
{{ end }}
flannel:
  interface: bond1
  etcd_endpoints: {{.etcd_endpoints}}
  network_config: '{ "Network": "10.1.0.0/16" }'
update:
  group: stable
locksmith:
  reboot_strategy: etcd-lock
  etcd_endpoints: {{.etcd_endpoints}}
networkd:
  units:
    - name: 00-bond0-slaves.network
      contents: |
        [Match]
        Driver=bnx2
        Driver=igb
        Driver=e1000*
        [Network]
        Bond=bond0
    - name: 00-bond1-slaves.network
      contents: |
        [Match]
        Driver=mlx4*
        Driver=ixgbe
        [Network]
        Bond=bond1
        [Link]
        MTUBytes=9000
    - name: 10-bond0.netdev
      contents: |
        [NetDev]
        Name=bond0
        Kind=bond
    - name: 10-bond1.netdev
      contents: |
        [NetDev]
        Name=bond1
        Kind=bond
    - name: 20-bond0.network
      contents: |
        [Match]
        Name=bond0
        [Network]
        DHCP=false
        Address={{.bond0_ipv4}}/24
        Gateway=192.168.20.1
        DNS=192.168.2.10
    - name: 20-bond1.network
      contents: |
        [Match]
        Name=bond1
        [Network]
        DHCP=false
        Address={{.bond1_ipv4}}/24
        [Link]
        MTUBytes=9000

{{ if index . "ssh_authorized_keys" }}
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        {{ range $element := .ssh_authorized_keys }}
        - {{$element}}
        {{end}}
{{end}}
